version: '3.9'
services:
  grape1:
    image: node:20-alpine
    working_dir: /app
    command: ["node", "grapes/grape1.js"]
    volumes: ["./grapes:/app/grapes"]
    networks: ["mesh"]

  grape2:
    image: node:20-alpine
    working_dir: /app
    command: ["node", "grapes/grape2.js"]
    volumes: ["./grapes:/app/grapes"]
    networks: ["mesh"]
    depends_on: ["grape1"]

  mysql :configs:
    image: mysql:8
    environment: 
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: testing
    ports: ["3306:3306"]
    volumes: [mysql_data:/var/lib/mysql]
    networks: ["mesh"]

  mongo: 
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
    networks: ["mesh"]

  order-svc: 
    image: node:20-alpine
    working_dir: /app
    volumes: ["./order-svc:/app", "./shared:/app/shared"]
    command: ["sh", "-c"," npm i && node server.js"]
    env_file: ["./order-svc/.env"]
    networks: ["mesh"]
    depends_on: ["grape1", "grape2", "mysql"]

  marketdata-svc:
    image: node:20-alpine
    working_dir: /app
    volumes: ["./marketdata-svc:/app", "./shared:/app/shared"]
    command: ["sh", "-c", "npm i && node server.js"]
    env_file: ["marketdata-svc/.env"]
    networks: ["mesh"]
    depends_on: [grape1, grape2, mongo]

  risk-worker:
    image: node:20-alpine
    working_dir: /app
    volumes: ["./risk-worker:/app", "./shared:/app/shared"]
    command: ["sh", "-c", "npm i && node server.js"]
    networks: ["mesh"]
    depends_on: [grape1, grape2]

  gateway:
    image: node:20-alpine
    working_dir: /app
    volumes: ["./gateway:/app", "./shared:/app/shared"]
    command: ["sh", "-c", "npm i && node server.js"]
    env_file: ["gateway/.env"]
    ports: ["8080:8080"]
    networks: ["mesh"]
    depends_on: [order-svc, marketdata-svc]

volumes:
  mysql_data:
  mongo_data:

networks:
  mesh: