CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  balance_usd DECIMAL(18,8) NOT NULL DEFAULT 10000.0
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  side ENUM('BUY','SELL') NOT NULL,
  type ENUM('LIMIT','MARKET') NOT NULL,
  price DECIMAL(18,8),
  qty DECIMAL(18,8) NOT NULL,
  status ENUM('NEW','REJECTED','FILLED','PARTIALLY_FILLED','CANCELLED') NOT NULL DEFAULT 'NEW',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);